import './globals.css'
import type { Metadata } from 'next'
import { Inter, Sawarabi_Mincho, Noto_Sans_JP } from 'next/font/google'
import { LanguageProvider } from './LanguageContext'
import { Analytics } from '@vercel/analytics/react';

const inter = Inter({ subsets: ['latin'] })
const sawarabiMincho = Sawarabi_Mincho({ weight: '400', subsets: ['latin'] })
const notoSansJP = Noto_Sans_JP({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={sawarabiMincho.className}>
        <LanguageProvider>
          {children}
        </LanguageProvider>
        <Analytics />
      </body>
    </html>
  )
}
